import type {Metadata} from "next";


export const metadata: Metadata = {
    title: "Restaurant QR | Login",
    description: "Generated by create next restaurant",
};

export default function RootLayout({
   children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <section className="bg-gray-50 min-h-screen flex items-center justify-center">
            {children}
        </section>
    );
}
