import type {Metadata} from "next";
import React, {Suspense} from "react";
import SidebarComponent from "@/components/navbar/sidebar";
import {RiArrowDownSLine, RiCheckboxBlankCircleFill, RiNotification2Line, RiSearchLine} from "react-icons/ri";
import {Input} from "@/components/ui/input";
import Loading from "@/app/dashboard/loading";
import {ThemeSwitch} from "@/components/navbar/ThemeSwitch";
import {DashboardHeader} from "@/components/navbar/DashboardHeader";

export const metadata: Metadata = {
    title: "Restaurant QR | Panel",
    description: "Generated by create next restaurant",
};
export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    //const responsiveBreakpoint: string = "sm:bg-indigo-500 md:bg-red-600 lg:bg-green-300 xl:bg-blue-600 2xl:bg-gray-800";
    return (
        <Suspense fallback={<Loading/>}>
            <div className={"min-h-screen grid grid-cols-1 md:grid-cols-5 lg:grid-cols-7"}>
                <SidebarComponent/>
                <div
                    className={"lg:col-span-6 md:col-span-4 col-span-1 md:grid-cols-3"}>
                    {/* Header   */}
                    <DashboardHeader/>
                    {/*Dashboard content*/}
                    <div className="grid grid-cols-3 p-12 gap-2">
                        {children}
                    </div>
                </div>
            </div>
        </Suspense>
    );
}