name: Deploy

on:
  pull_request:
    branches:
      - release

jobs:
  deploy:
    runs-on: [self-hosted, supa]
    environment: supa

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        env:
          DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          APP_DNS_DOMAIN: ${{ secrets.APP_DNS_DOMAIN }}
          APP_TLS_MAIL: ${{ secrets.APP_TLS_MAIL }}
        run: |
          docker compose -f docker-compose.pro.yaml pull
          docker compose -f docker-compose.pro.yaml build --build-arg DOTENV_KEY=${DOTENV_KEY}
      - name: Deploy containers with rolling update
        run: |
          docker compose -f docker-compose.pro.yaml up -d --no-deps
        env:
          DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          APP_DNS_DOMAIN: ${{ secrets.APP_DNS_DOMAIN }}
          APP_TLS_MAIL: ${{ secrets.APP_TLS_MAIL }}

      - name: Prune unused Docker images
        run: docker image prune -f