name: Deployment PRO
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    timeout-minutes: 5
    name: Run tests
    runs-on: ubuntu-latest
    environment: pro
    strategy:
      matrix:
        node-version: [ 20.12.2 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: false
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
#      - name: Install Playwright Browsers
#        run: npx playwright install --with-deps
      - name: Setup .env file
        run: npx dotenv-vault local decrypt ${{secrets.DOTENV_KEY}} > .env
#      - name: Run Playwright tests
#        run: npx playwright test
      - name: Build
        run: npm run build
      - name: Build failed
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Han fallado los tests de PR a PRO.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
#  notification_start:
#    if: github.ref == 'refs/heads/main'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Notify start action
#        uses: rjstone/discord-webhook-notify@v1
#        with:
#          severity: info
#          color: '#0059ff'
#          details: New push to repository click2eat-panel on environment PRO
#          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
#  deploy_pro:
#    name: Deploy to production
#    if: github.ref == 'refs/heads/main'
#    needs:
#      - notification_start
#    runs-on: [self-hosted, prod]
#    environment: pro
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#        with:
#          clean: false
#      - name: Set up Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: 20.12.2
#          cache: 'npm'
#      - name: Install dependencies
#        run: npm ci
#      - name: Setup .env file
#        run: npx dotenv-vault local decrypt ${{secrets.DOTENV_KEY}} > .env
#      - name: Build
#        run: node -r dotenv/config ./node_modules/.bin/next build
#      - name: Reload application
#        run: pm2 reload 0
#      - name: Deploy Success
#        uses: rjstone/discord-webhook-notify@v1
#        if: success()
#        with:
#          severity: info
#          details: Desplegado producción con éxito!
#          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
#      - name: Deploy failed
#        uses: rjstone/discord-webhook-notify@v1
#        if: failure()
#        with:
#          severity: error
#          details: Ha fallado el despliegue a producción
#          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}