name: Deploy

on:
  pull_request:
    branches:
      - release

jobs:
  deploy:
    runs-on: [self-hosted, supa]
    environment: supa

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy with docker-compose
        env:
          DOTENV_KEY: ${{ secrets.DOTENV_KEY_PROD }}
        run: |
          docker compose -f docker-compose.pro.yaml build --build-arg DOTENV_KEY=${DOTENV_KEY}
          docker compose -f docker-compose.pro.yaml up -d --remove-orphans

      - name: Prune old images
        run: docker image prune -af