name: Deploy

on:
  pull_request:
    branches:
      - release

jobs:
  deploy:
    runs-on: [self-hosted, supa]
    environment: supa

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          DOTENV_KEY: ${{ secrets.DOTENV_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t nextjs-restaurant:${{ github.sha }} -f docker/app/app.dockerfile .
          docker tag nextjs-restaurant:${{ github.sha }} nextjs-restaurant:latest

      - name: Deploy with Docker Compose
        run: |
          docker compose -f docker-compose.pro.yaml up -d --scale app=2 --no-deps app
          docker compose -f docker-compose.pro.yaml up -d
        env:
          DOTENV_KEY: ${{ secrets.DOTENV_KEY }}

      - name: Clean up old images
        run: docker image prune -af